import { useEffect, useId, useRef, useState } from 'react'
import { Html5Qrcode, Html5QrcodeSupportedFormats } from 'html5-qrcode'
import { Button } from './ui/Button'
import { StatusNote } from './ui/StatusNote'

// Camera scanning for Barcode #2 (§2.2: Code128, generated by
// barcodeLabel.ts/Barcode2Display.tsx) — UX pass prompt 1/2's one new
// feature. Self-contained: owns its own open/closed state, mounts the
// camera only while open, and calls `onDecode` with the raw decoded string
// for every successful read — the CALLER is responsible for feeding that
// string into the exact same handler the manual input already uses (see
// OmborChiqimTab.tsx's `processBarcode`), so a camera read behaves
// identically to typing the same code, including a voided/claimed/wrong-
// stage barcode failing exactly the same way.
//
// Restricted to CODE_128 only (`formatsToSupport`) — the one format this
// app ever generates, and narrowing it measurably speeds up + steadies the
// decoder versus scanning for every supported symbology on every frame.
//
// Continuous-scan, not scan-once: `Html5Qrcode.start()` keeps calling
// `onScanSuccess` for as long as a code is in frame, which would otherwise
// fire duplicate lookups for a barcode the operator is still holding
// steady in view — debounced below (same code within 1.5s is ignored;
// `resolveScan`'s own `duplicate` check is the real guard once a scan
// actually lands, this is just to avoid hammering Supabase with repeat
// lookups of a code that's already been accepted or rejected once).
export function BarcodeCameraScanner({ onDecode }: { onDecode: (code: string) => void }) {
  const [open, setOpen] = useState(false)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const regionId = `barcode-camera-${useId().replace(/[^a-zA-Z0-9]/g, '')}`
  const instanceRef = useRef<Html5Qrcode | null>(null)
  const lastCodeRef = useRef<{ code: string; at: number } | null>(null)
  const onDecodeRef = useRef(onDecode)
  onDecodeRef.current = onDecode

  useEffect(() => {
    if (!open) return
    let cancelled = false
    setCameraError(null)
    const instance = new Html5Qrcode(regionId, {
      verbose: false,
      formatsToSupport: [Html5QrcodeSupportedFormats.CODE_128],
    })
    instanceRef.current = instance

    instance
      .start(
        { facingMode: 'environment' },
        { fps: 10, qrbox: { width: 280, height: 120 } },
        (decodedText) => {
          const now = Date.now()
          const last = lastCodeRef.current
          if (last && last.code === decodedText && now - last.at < 1500) return
          lastCodeRef.current = { code: decodedText, at: now }
          onDecodeRef.current(decodedText)
        },
        () => {
          // Fires once per frame with no code in view — expected noise,
          // not an error condition. Deliberately ignored.
        },
      )
      .then(() => {
        if (cancelled) {
          instance
            .stop()
            .catch(() => {})
            .then(() => instance.clear())
        }
      })
      .catch(() => {
        if (cancelled) return
        setCameraError(
          'Kameraga ruxsat berilmadi yoki kamera topilmadi. Pastdagi maydonga qo\'lda kiriting yoki skaner qurilmasidan foydalaning.',
        )
      })

    return () => {
      cancelled = true
      if (instance.isScanning) {
        instance
          .stop()
          .catch(() => {})
          .finally(() => {
            try {
              instance.clear()
            } catch {
              // already cleared/torn down
            }
          })
      }
    }
  }, [open, regionId])

  if (!open) {
    return (
      <Button variant="primary" size="lg" fullWidth onClick={() => setOpen(true)}>
        📷 Kamerani yoqish
      </Button>
    )
  }

  return (
    <div className="space-y-2 rounded-md border border-slate-300 bg-slate-900 p-2 dark:border-slate-700">
      <div id={regionId} className="mx-auto max-w-xs overflow-hidden rounded-md [&_video]:rounded-md" />
      {cameraError && (
        <div className="rounded-md bg-white p-2 dark:bg-slate-800">
          <StatusNote tone="problem">{cameraError}</StatusNote>
        </div>
      )}
      <Button variant="secondary" size="md" fullWidth onClick={() => setOpen(false)} className="bg-white dark:bg-slate-800">
        Kamerani yopish
      </Button>
    </div>
  )
}
