import { useEffect, useRef, useState } from 'react'
import { BarcodeDetector as PonyfillBarcodeDetector, prepareZXingModule } from 'barcode-detector/ponyfill'
import zxingReaderWasmUrl from 'zxing-wasm/reader/zxing_reader.wasm?url'
import { Button } from './ui/Button'
import { StatusNote } from './ui/StatusNote'

// Camera scanning for Barcode #2 (§2.2: Code128, generated by
// barcodeLabel.ts/Barcode2Display.tsx). Self-contained: owns its own
// open/closed state, mounts the camera only while open, and calls
// `onDecode` with the raw decoded string for every successful read — the
// CALLER is responsible for feeding that string into the exact same
// handler the manual input already uses (see OmborChiqimTab.tsx's
// `processBarcode`), so a camera read behaves identically to typing the
// same code, including a voided/claimed/wrong-stage barcode failing
// exactly the same way.
//
// 🔒 Replaces html5-qrcode — confirmed on real hardware to open the
// camera but never decode a real printed CODE_128 label, even with a
// resolution hint (DECISIONS.md "Camera scanner" entries). Uses the
// native BarcodeDetector where the browser has it (Chrome/Samsung
// Internet on Android — hardware-accelerated, meaningfully stronger on
// 1D), and falls back to the `barcode-detector` ponyfill (ZXing-C++
// wasm) everywhere else — desktop browsers, iOS Safari, Firefox — none
// of which implement BarcodeDetector natively. Both share the identical
// `detect(video)` shape, so the scan loop below never needs to know
// which one it's holding.
//
// The ponyfill's wasm defaults to fetching from a CDN at runtime (see
// zxing-wasm's own built-in default locateFile, which points at
// fastly.jsdelivr.net — dead in the water with no signal, and an
// offline-first violation even with signal), which would break this app's
// "works offline once cached" requirement (PHASE0.md Part E) —
// prepareZXingModule below points it at the copy Vite bundles into this
// build instead (also added to vite.config.ts's PWA `globPatterns` so the
// service worker actually precaches it for the web build).
//
// Logged, not just set: this line is the #1 suspect for "camera opens but
// never decodes" in the Capacitor Android WebView (DECISIONS.md "Camera
// scanner in the Android WebView"). If this override silently failed to
// apply for any reason, the library falls through to its CDN default
// instead of throwing — with no signal that's a silent, permanent dead
// end that looks identical to "no barcode in frame", which is exactly
// this bug's symptom. This log confirms which URL is actually in effect.
console.log('[BarcodeCameraScanner] zxing wasm locateFile ->', zxingReaderWasmUrl)
prepareZXingModule({
  overrides: {
    locateFile: (path: string) => (path.endsWith('.wasm') ? zxingReaderWasmUrl : path),
  },
})

interface Detector {
  detect(image: HTMLVideoElement): Promise<Array<{ rawValue: string }>>
}

// Scan-outcome feedback, shown as a banner over the video itself (not just
// below it) — the operator's eyes are on the camera while aiming, not the
// page below. Caller (OmborChiqimTab.tsx's processBarcode) owns the
// lifecycle: sets this from the exact same success/failure branches that
// already drive scanError/scannedByRequest, so this is presentation on top
// of unchanged decision logic, not a new outcome path.
export interface ScanFeedback {
  tone: 'ok' | 'problem'
  message: string
}

// Solid, high-opacity colors — deliberately NOT toneStyles' own bg/text
// pair (those are subtle/light, meant to sit on a white card background;
// illegible overlaid on an arbitrary live camera feed, which can be any
// color behind it).
const FEEDBACK_STYLES: Record<ScanFeedback['tone'], string> = {
  ok: 'bg-emerald-600/95 text-white',
  problem: 'bg-red-600/95 text-white',
}

// Logged, not silent: which path a given session took is the #1 thing
// needed to diagnose "opens but never decodes" on a new environment (see
// DECISIONS.md). BarcodeDetector's presence in Android System WebView is
// unverified for THIS app's embedded context — MDN's compat data "mirrors"
// Chrome for Android's, but that's inferred from the shared Chromium
// version, not independently confirmed for a WebView embedded in a
// third-party app, where the underlying Play Services ML Kit barcode
// model has in the past been reported as inconsistently available.
// Deliberately not auto-falling-back from native to the ponyfill at
// runtime here (e.g. on a thrown/empty detect()) — that would hide the
// real answer instead of surfacing it. If the device test shows native
// chosen but still never decoding, forcing the ponyfill on native Android
// specifically is the next, now well-targeted, fix.
//
// 🔒 qr_code added alongside code_128 (DECISIONS.md "Barcode format:
// CODE_128 -> QR") — QR is the new target format (barcodeLabel.ts,
// P1PrinterPlugin.java), but code_128 stays so any already-printed 1D
// labels still on pallets keep scanning during the transition. Both native
// BarcodeDetector and the zxing-wasm ponyfill support QR natively — no new
// dependency, purely a formats-list addition.
function createDetector(): Detector {
  const native = (window as unknown as { BarcodeDetector?: new (opts: { formats: string[] }) => Detector }).BarcodeDetector
  console.log('[BarcodeCameraScanner] detector path ->', native ? 'native BarcodeDetector' : 'ponyfill (zxing-wasm)')
  const Ctor = native ?? PonyfillBarcodeDetector
  return new Ctor({ formats: ['code_128', 'qr_code'] })
}

const SCAN_INTERVAL_MS = 100 // ~10fps — matches the previous html5-qrcode `fps: 10`

export function BarcodeCameraScanner({
  onDecode,
  feedback,
}: {
  onDecode: (code: string) => void
  feedback?: ScanFeedback | null
}) {
  const [open, setOpen] = useState(false)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const lastCodeRef = useRef<{ code: string; at: number } | null>(null)
  const onDecodeRef = useRef(onDecode)
  onDecodeRef.current = onDecode

  useEffect(() => {
    if (!open) return
    let cancelled = false
    let stream: MediaStream | null = null
    let videoEl: HTMLVideoElement | null = null
    let timeoutId: number | null = null
    let loggedFirstReadyFrame = false
    let lastLoggedError: string | null = null
    setCameraError(null)

    const detector = createDetector()

    navigator.mediaDevices
      .getUserMedia({
        video: {
          facingMode: 'environment',
          width: { ideal: 1280 },
          height: { ideal: 720 },
        },
        audio: false,
      })
      .then((mediaStream) => {
        if (cancelled) {
          mediaStream.getTracks().forEach((track) => track.stop())
          return
        }
        stream = mediaStream
        videoEl = videoRef.current
        if (!videoEl) return
        videoEl.srcObject = mediaStream
        videoEl.play().catch(() => {})

        const scanLoop = async () => {
          if (cancelled) return
          const currentVideo = videoRef.current
          if (currentVideo && currentVideo.readyState >= currentVideo.HAVE_CURRENT_DATA) {
            // Requirement #3 (do frames reach the decoder at all): logged
            // once, not every ~100ms — confirms the video element itself is
            // producing decodable frames in this environment, same as it
            // does in a browser tab, before ever blaming the detector.
            if (!loggedFirstReadyFrame) {
              loggedFirstReadyFrame = true
              console.log(
                '[BarcodeCameraScanner] first frame ready, readyState =',
                currentVideo.readyState,
                'size =',
                `${currentVideo.videoWidth}x${currentVideo.videoHeight}`,
              )
            }
            try {
              const results = await detector.detect(currentVideo)
              const decodedText = results[0]?.rawValue
              if (decodedText) {
                const now = Date.now()
                const last = lastCodeRef.current
                if (!last || last.code !== decodedText || now - last.at >= 1500) {
                  lastCodeRef.current = { code: decodedText, at: now }
                  onDecodeRef.current(decodedText)
                }
              }
            } catch (err) {
              // Genuinely no code in this frame does NOT throw (an empty
              // `results` array does) — this catch is only real failures:
              // a wasm init error, a native-API throw, etc. Previously
              // fully silent, which is exactly what made "opens but never
              // decodes" indistinguishable from normal per-frame noise.
              // Logged once per distinct message, not every ~100ms, so a
              // persistent failure is still visible without flooding
              // logcat.
              const message = err instanceof Error ? err.message : String(err)
              if (message !== lastLoggedError) {
                lastLoggedError = message
                console.error('[BarcodeCameraScanner] detect() failed:', err)
              }
            }
          }
          if (!cancelled) timeoutId = window.setTimeout(scanLoop, SCAN_INTERVAL_MS)
        }
        scanLoop()
      })
      .catch(() => {
        if (cancelled) return
        setCameraError(
          'Kameraga ruxsat berilmadi yoki kamera topilmadi. Pastdagi maydonga qo\'lda kiriting yoki skaner qurilmasidan foydalaning.',
        )
      })

    return () => {
      cancelled = true
      if (timeoutId !== null) window.clearTimeout(timeoutId)
      stream?.getTracks().forEach((track) => track.stop())
      if (videoEl) videoEl.srcObject = null
    }
  }, [open])

  if (!open) {
    return (
      <Button variant="primary" size="lg" fullWidth onClick={() => setOpen(true)}>
        📷 Kamerani yoqish
      </Button>
    )
  }

  return (
    <div className="space-y-2 rounded-md border border-slate-300 bg-slate-900 p-2 dark:border-slate-700">
      <div className="relative mx-auto max-w-xs overflow-hidden rounded-md">
        <video ref={videoRef} className="block w-full" autoPlay muted playsInline />
        {/* Aiming guide — html5-qrcode's own `qrbox` drew this; lost when it
            was replaced by BarcodeDetector's plain <video> (see file header,
            commit 755746c), restored square (DECISIONS.md "Barcode format:
            CODE_128 -> QR") — the wide 280:120 rectangle was tuned for a 1D
            barcode; QR is the new target format and needs a square target
            instead. The huge spread box-shadow dims everything outside the
            square, the classic scan-mask look, no clip-path/SVG needed.
            Decorative only: the decoder below still reads the full frame —
            cropping to this region would mean an extra canvas draw every
            ~100ms in the scan loop (off limits, see file header) for a
            boundary the operator's own aim already narrows in practice. */}
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div className="aspect-square w-[65%] max-w-[220px] rounded-md border-[3px] border-white/90 shadow-[0_0_0_9999px_rgba(0,0,0,0.35)]" />
        </div>
        {feedback && (
          <div
            className={`absolute inset-x-0 bottom-0 px-2 py-1.5 text-center text-sm font-medium ${FEEDBACK_STYLES[feedback.tone]}`}
          >
            {feedback.message}
          </div>
        )}
      </div>
      {cameraError && (
        <div className="rounded-md bg-white p-2 dark:bg-slate-800">
          <StatusNote tone="problem">{cameraError}</StatusNote>
        </div>
      )}
      <Button variant="secondary" size="md" fullWidth onClick={() => setOpen(false)} className="bg-white dark:bg-slate-800">
        Kamerani yopish
      </Button>
    </div>
  )
}
